In [2]:
print('i'+ 'love'+'coding')

ilovecoding


first_name = "Oke"
last_name = "Ejiro"
full_name = first_name + "" + last_name
print(full_name)

first_name = "Oke"
last_name = "Ejiro"
full_name = first_name + "" + last_name
print(full_name)

In [4]:
first_name = "Oke"
print('my name is {}'.format(first_name))

my name is Oke


In [5]:
print("Hello {} , you are +{} today". format(first_name, 25))

Hello Oke , you are +25 today


In [6]:
first_name = "oke"
print(first_name.title())

Oke


In [7]:
print("LOve aNd LiGhT".upper())

LOVE AND LIGHT


In [8]:
print("LOve aNd LiGhT".lower())

love and light


In [9]:
word = "Hello there!"
print(word.replace('!', '.'))

Hello there.


In [10]:
sentence = "welcome to Hamoye Externship"
print(sentence.find('ship'))

24


In [11]:
x = 10
y = 4
if x > y:
  print("x is greater than y")

x is greater than y


In [20]:
x = 4
y = 1
if x > y:
  print("x is greater than y")
else:
    print("y is greater than x")

x is greater than y


In [ ]:
x = 1
y = 3

In [14]:
class Car:
  pass

In [15]:
class Car:
  def __init__(self):
    pass

In [18]:
class Car:
  def __init__(self, color, style):
    self.color = color
    self.style = style
    c = Car('Sedan', 'Black')

In [26]:
class Car:
  wheels = 4
  def __init__(self, color, style):
    self.color = color
    self.style = style
    def showDescription(self):
      print("This car is a", self.color, self.style)

      def changeColor(self, color):
        self.color = color
        c = Car('Black', 'Sedan')
        c.showDescription()
        c.changeColor('White')
        c.showDescription()

In [ ]:
class Car:
  def __init__(self, color, style):
    self.color = color
    self.style = style
    c = Car('Sedan', 'Black')

In [28]:
# convention for importing numpy
import numpy as np
arr = [6, 7, 8, 9]
print(type(arr))

<class 'list'>


In [9]:
import numpy as np
arr = [6,7,8,9]
print(type(arr))
a = np.array(arr)
print(type(a))
print(a.shape)
print(a.dtype)
print(a.ndim)

<class 'list'>
<class 'numpy.ndarray'>
(4,)
int64
1


In [13]:
b = np.array([[1,2,3],[4,5,6]])
print(b)
print(b.ndim)
b.shape

[[1 2 3]
 [4 5 6]]
2


(2, 3)

In [ ]:
import numpy as np
arr = [6,7,8,9]
print(type(arr))
a = np.array(arr)
print(type(a))
print(a.shape)
print(a.dtype)
print(a.ndim)
a[0] 

b = np.array([[1,2,3],[4,5,6]])
print(b)
print(a)
print(b.ndim)
b.shape


In [6]:
arr = [6,7,8,9]
a[0]
a[3]
b = np.array([[1,2,3],[4,5,6]])
b[0,0]
b[1,2]

6

In [32]:
np.random.random((2,3))
np.zeros((2,3))
np.ones((2,3))
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
c=np.array([[9.0,8.0,7.0],[1.0,2.0,3.0]])
d=np.array([[4.0,5.0,6.0],[9.0,8.0,7.0]])

print(c+d)
c*d
5/d
c**2
c*2

[[13. 13. 13.]
 [10. 10. 10.]]


array([[18., 16., 14.],
       [ 2.,  4.,  6.]])

In [48]:
e = np.array([[10,11,12],[13,14,15],[16,17,18],[19,20,21]])
e[:3,:2]
e[[2,0,3,1],[2,1,0,2]]
e[e>15]

array([16, 17, 18, 19, 20, 21])

In [1]:
a[0]

NameError: ignored